name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5.0.1
    - uses: actions/setup-node@v4.0.2
    - name: Install node-sass
      run: npm install -g sass-loader node-sass
    - name: Check sass version
      run: sass --version
    - name: Build the Docker image
      run: make docker_image
